#!/bin/sh

# Core extensions
alias ls="ls -A"
alias ll="ls -lh"

# Git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git duet-commit -v"
alias gd="git diff"
alias gl="git log"

# Utilities
alias be="bundle exec"
alias bx="bundle exec"
