#!/bin/sh

alias ls="ls -A"
alias ll="ls -lh"

alias eda="emacs --daemon"
alias e="emacsclient -t"
alias ek="emacsclient -e '(kill-emacs)'"

alias startgres="postgres -D /usr/local/var/postgres"
alias startredis="redis-server /usr/local/etc/redis.conf"

alias be="bundle exec"

# git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit -v"
alias gd="git diff"
alias gl="git log"
alias chead="git commit --amend -CHEAD"

alias ts="ruby ~/.vim/bundle/test_server/test_server.rb"


# Current projects
alias code="cd ~/code"
alias api="cd ~/code/json-api"
alias js="cd ~/code/javascript/"
alias cljs="cd ~/code/clojurescript/"
alias clj="cd ~/code/clojure/"
alias fb="cd ~/code/foosboard"
alias ms="cd ~/code/MachSpiel"
alias blog="cd ~/code/ccoriander"
alias ios="cd ~/code/ios"

alias stamp="date +'%Y_%m_%d_%H%M%S'"
